### ISSUE TITLE
Instance name instead of Keypair Name

### ISSUE THREAD

**Issue by rfrank14** [JamesMatchett/AWS-Discord-Bot#12]
Thanks for building this, i'm using it at the moment.

One thing i noticed is that its returning key pair name for server name, thinking it might be better to get the instance name that's described through management console. The name is just a tag with the key 'Name'. 

If you are accepting pull requests i can do it up.

**Comment by JamesMatchett** [comment]
Hey there, I'm really glad to hear you're getting some use out of it :D 

I'm more than happy to accept pull requests as long as they benefit the program, thank you very much for offering!

Looking forward to seeing it, and if you're unable to do it, I'm more than happy to make it :) 

-J

**Comment by JamesMatchett** [comment]
Fixed in #13 

Thanks @rfrank14 !
